path: D:\TEC\Sem-6\Mini Project
train: D:\TEC\Sem-6\Mini Project\train
val: D:\TEC\Sem-6\Mini Project\valid
test: D:\TEC\Sem-6\Mini Project\test

names:
  0: bottle
  1: mobile-phone
  2: device
  3: face
  4: live
  5: mask
  6: photo
  7: Chair
  8: NotChair